/**
 * {{entityName}} entity.
 *
 * Generated by Scaffoldix pack: {{pack.name}}
 */
export interface {{entityName}} {
  id: string;
  createdAt: string;
}

export class {{entityName}}Service {
  private readonly items: Map<string, {{entityName}}> = new Map();

  create(id: string): {{entityName}} {
    const item: {{entityName}} = {
      id,
      createdAt: new Date().toISOString(),
    };
    this.items.set(id, item);
    return item;
  }

  findById(id: string): {{entityName}} | undefined {
    return this.items.get(id);
  }

  findAll(): {{entityName}}[] {
    return Array.from(this.items.values());
  }

  delete(id: string): boolean {
    return this.items.delete(id);
  }
}
