/**
 * Init command — scaffold a new Scaffoldix pack interactively.
 *
 * Creates a new pack directory with the required structure:
 *   archetype.yaml, templates/default/, and an example template file.
 *
 * Usage:
 *   scaffoldix init [directory]
 *
 * @module
 */

import * as path from "node:path";
import * as fs from "node:fs/promises";
import { Command } from "commander";
import { getCliUx } from "../ux/CliUx.js";

// Default archetype.yaml template
function buildArchetypeYaml(packName: string, packVersion: string, description: string): string {
  return `pack:
  name: ${packName}
  version: "${packVersion}"
  description: "${description}"

archetypes:
  - id: default
    description: "Default archetype"
    templateRoot: templates/default
    inputs:
      - name: name
        type: string
        required: true
        prompt: "What is the name?"
        description: "Name used in generated files"
    checks: []
    postGenerate: []
`;
}

// Example template file
const EXAMPLE_TEMPLATE = `# {{name}}

Generated by Scaffoldix.
`;

/**
 * Builds the `init` command.
 *
 * @returns Configured Commander command
 */
export function buildInitCommand(): Command {
  return new Command("init")
    .description("Scaffold a new Scaffoldix pack interactively")
    .argument("[directory]", "Directory to create the pack in (default: current directory)")
    .option("--name <name>", "Pack name")
    .option("--version <version>", "Pack version", "0.1.0")
    .option("--description <description>", "Pack description", "A Scaffoldix pack")
    .option("--yes", "Skip prompts and use provided options / defaults", false)
    .addHelpText(
      "after",
      `
Examples:
  scaffoldix init ./my-pack
  scaffoldix init --name my-pack --yes`,
    )
    .action(
      async (
        directory: string | undefined,
        options: { name?: string; version: string; description: string; yes: boolean },
      ) => {
        const ux = getCliUx();

        try {
          const targetDir = path.resolve(process.cwd(), directory ?? ".");

          // Derive default pack name from directory
          const defaultName = path.basename(targetDir);

          let packName = options.name ?? defaultName;
          let packVersion = options.version;
          let packDescription = options.description;

          // Interactive prompts when not in --yes mode
          if (!options.yes) {
            const { text, confirm } = await import("@clack/prompts");

            const inputName = await text({
              message: "Pack name:",
              initialValue: packName,
              validate: (v) => (v.trim().length === 0 ? "Name is required" : undefined),
            });
            if (typeof inputName !== "string") {
              ux.info("Cancelled.");
              return;
            }
            packName = inputName;

            const inputVersion = await text({
              message: "Pack version:",
              initialValue: packVersion,
              validate: (v) =>
                /^\d+\.\d+\.\d+/.test(v) ? undefined : "Must follow semver (e.g. 0.1.0)",
            });
            if (typeof inputVersion !== "string") {
              ux.info("Cancelled.");
              return;
            }
            packVersion = inputVersion;

            const inputDesc = await text({
              message: "Pack description:",
              initialValue: packDescription,
            });
            if (typeof inputDesc !== "string") {
              ux.info("Cancelled.");
              return;
            }
            packDescription = inputDesc;

            const ok = await confirm({
              message: `Create pack "${packName}" in ${targetDir}?`,
            });
            if (!ok) {
              ux.info("Cancelled.");
              return;
            }
          }

          // Create directory structure
          const templatesDir = path.join(targetDir, "templates", "default");
          await fs.mkdir(templatesDir, { recursive: true });

          // Write archetype.yaml
          const manifestPath = path.join(targetDir, "archetype.yaml");
          await fs.writeFile(
            manifestPath,
            buildArchetypeYaml(packName, packVersion, packDescription),
            "utf-8",
          );

          // Write example template file
          const exampleFile = path.join(templatesDir, "README.md");
          await fs.writeFile(exampleFile, EXAMPLE_TEMPLATE, "utf-8");

          ux.success(`Pack "${packName}" created at ${targetDir}`);
          ux.detail("archetype.yaml — pack manifest");
          ux.detail("templates/default/README.md — example template");
          ux.info("");
          ux.info(`Next steps:`);
          ux.detail(`scaffoldix pack add ${targetDir}`);
          ux.detail(`scaffoldix generate ${packName}:default`);
        } catch (err) {
          const message = err instanceof Error ? err.message : String(err);
          ux.error(`Failed to create pack: ${message}`);
          process.exitCode = 1;
        }
      },
    );
}
